name: Build

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    name: Build website
    runs-on: windows-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2.4.0

      - name: "Install NuGet"
        uses: NuGet/setup-nuget@v1.0.5

      - name: "Install DocFX"
        run: |
          if (Test-Path "C:\DocFx\" -PathType Container) {
            Remove-Item C:\DocFX\*.* -Recurse -Force
          }
          nuget install docfx.console -OutputDirectory C:\DocFX -NoCache -NonInteractive

      - name: "Build English Website"
        run: |
          cd en
          $docfxpath = (Get-ChildItem C:\DocFX\ -Filter docfx.exe -Recurse).FullName
          Start-Process -FilePath $docfxpath -ArgumentList build -WorkingDirectory (Get-Location) -NoNewWindow -Wait