name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy Website"
    if: github.event.pull_request_target.merged == true
    runs-on: windows-latest
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: website
          path: website

      - name: "Upload to website"
        uses: garygrossgarten/github-action-scp@release
        with:
          local: website
          remote: /opt/bitnami/apps/navxdocs/htdocs
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
