name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy Website"
    runs-on: windows-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2.4.0

      - name: "download website artifact"
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI-PR.yml
          workflow_conclusion: success
          name: website
          path: ./website/

      - name: "Get Public IP"
        id: ip
        uses: haythem/public-ip@v1.2

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED }}
          enable-AzPSSession: true

      - name: "Add public IP to allowed IPs"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $publicIp = (Get-AzPublicIpAddress | Where-Object {$_.IpAddress -eq "${{ secrets.HOST }}" })
            if ($null -eq $publicIp) {
                throw "Public not found"
            }
            $nic = Get-AzNetworkInterface | Where-Object { $_.IpConfigurations.PublicIpAddress.Id -eq $publicIp.Id }
            if ($null -eq $nic) {
                throw "Network Interface not found"
            }
            $nsg = Get-AzResource -ResourceId $nic.NetworkSecurityGroup.Id | Get-AzNetworkSecurityGroup
            if ($null -eq $nsg) {
                throw "Network Security Group not found"
            }
            $ruleExists = (Get-AzNetworkSecurityRuleConfig -NetworkSecurityGroup $nsg).Name.Contains("github")

            if ($ruleExists) {
                Set-AzNetworkSecurityRuleConfig -Name "github" -Description "github" -Access Allow -Protocol TCP -Direction Inbound -Priority 100 -SourceAddressPrefix ${{ steps.ip.outputs.ipv4 }} -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange 22 -NetworkSecurityGroup $nsg | Out-Null
            }
            else {
                $nsg | Add-AzNetworkSecurityRuleConfig -Name "github" -Description "github" -Access Allow -Protocol TCP -Direction Inbound -Priority 100 -SourceAddressPrefix ${{ steps.ip.outputs.ipv4 }} -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange 22 | Out-Null
            }

            $nsg | Set-AzNetworkSecurityGroup | Out-Null
          azPSVersion: "latest"
          
      - name: "Upload to website"
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          protocol: ftps
          local-dir: ./website/
          server-dir: opt/bitnami/apps/navxdocs/htdocs

      - name: "Remove public IP from allowed IPs"
        uses: azure/powershell@v1
        with:
          inlineScript:
            $publicIp = (Get-AzPublicIpAddress | Where-Object {$_.IpAddress -eq "${{ secrets.HOST }}" })
            if ($null -eq $publicIp) {
                throw "Public not found"
            }
            $nic = Get-AzNetworkInterface | Where-Object { $_.IpConfigurations.PublicIpAddress.Id -eq $publicIp.Id }
            if ($null -eq $nic) {
                throw "Network Interface not found"
            }
            $nsg = Get-AzResource -ResourceId $nic.NetworkSecurityGroup.Id | Get-AzNetworkSecurityGroup
            if ($null -eq $nsg) {
                throw "Network Security Group not found"
            }

            $ruleExists = (Get-AzNetworkSecurityRuleConfig -NetworkSecurityGroup $nsg).Name.Contains("github")
            if ($ruleExists) {
              Remove-AzNetworkSecurityRuleConfig -Name "github" -NetworkSecurityGroup $nsg | Out-Null
              $nsg | Set-AzNetworkSecurityGroup | Out-Null
            }
          azPSVersion: "latest"