name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Deploy Website"
    runs-on: windows-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "download website artifact"
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI-PR.yml
          workflow_conclusion: success
          name: website
          path: ./website/

      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CRED }}
          enable-AzPSSession: true

      - name: "Add Network Security Group"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Write-Host "Need to turn on basic authentication"
          azPSVersion: "latest"
          
      - name: "Upload to website"
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: '${{ secrets.HOST }}'
          port: 22
          username: '${{ secrets.SSH_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          localPath: './site/wwwroot'
          remotePath: '/site/wwwroot'
          
      - name: "Remove public IP from allowed IPs"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Write-Host "Need to turn off basic authentication"
          azPSVersion: "latest"
