name: $(BuildID)

resources:
- repo: self

variables:
  build.clean: all
  platform: x64

trigger:
  branches:
    include:
      - master

pr: none

stages:
- stage: Deploy
  displayName: 'Deploy website'
  jobs:
  - job: DeployWebsite
    displayName: 'Deploy Website'
    continueOnError: false
    pool: navxdefault
    workspace:
      clean: all
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Website Artifact'
      inputs:
        buildType: 'specific'
        project: 'f0d284ed-af49-4b2a-9d2e-01e485482d6e'
        definition: 34
        buildVersionToDownload: 'latest'
        artifactName: 'website'
        path: '$(Pipeline.Workspace)\website'

    - task: CopyFilesOverSSH@0
      displayName: 'Upload of website'
      condition: succeeded()
      inputs:
        sshEndpoint: NavxDocsWebsite
        sourceFolder: '$(Pipeline.Workspace)\website\'
        contents: '**'
        targetFolder: '/opt/bitnami/apps/navxdocs/htdocs'
        cleanTargetFolder: false
        overwrite: true
        failOnEmptySource: true
        flattenFolders: false