name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy Website"
    runs-on: windows-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2.4.0

      - name: "download website artifact"
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI-PR.yml
          workflow_conclusion: success
          name: website
          path: ./website/
          
      - name: "Upload to website"
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: '${{ secrets.HOST }}'
          port: 7394
          username: '${{ secrets.SSH_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          localPath: './website/'
          remotePath: '/opt/bitnami/apps/navxdocs/htdocs/'