name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Install NuGet"
        uses: NuGet/setup-nuget@v2

      - name: "Install DocFX"
        run: |
          if (Test-Path "C:\DocFx\" -PathType Container) {
            Remove-Item C:\DocFX\*.* -Recurse -Force
          }
          nuget install docfx.console -OutputDirectory C:\DocFX -NoCache -NonInteractive

      - name: "Build English Website"
        run: |
          cd en
          $docfxpath = (Get-ChildItem C:\DocFX\ -Filter docfx.exe -Recurse).FullName
          Start-Process -FilePath $docfxpath -ArgumentList build -WorkingDirectory (Get-Location) -NoNewWindow -Wait

      - name: "Assemble website"
        run: |
          if (!(Test-Path "./website/")) {
              New-Item -Path "./website/" -ItemType Directory -Force
          }
          Remove-Item -Path "./website/*" -Recurse
          New-Item -Path "./website/en" -ItemType Directory -Force
          Copy-Item -Path "./_site/images" -Destination "./website" -Recurse
          Copy-Item -Path "./BingSiteAuth.xml" -Destination "./website"
          Copy-Item -Path "./_site/search-stopwords.json" -Destination "./website"
          Copy-Item -Path "./_site/sitemap.xml" -Destination "./website"
          Copy-Item -Path "./_site/*" -Destination "./website/en" -Recurse

      - name: "Upload website artifact"
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./website/
          retention-days: 3

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          workflow: CI-PR.yml
          workflow_conclusion: success
          name: website
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C54C27F38F544BCBABD914FB088A03C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4DD92970278A4A5B88A1ECAB3ABDCED6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_517E1DE56CC14032836B1858AE41B6E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'navxdocs'
          slot-name: 'Production'
          package: .
          