name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          workflow: CI-PR.yml
          workflow_conclusion: success
          name: website
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C54C27F38F544BCBABD914FB088A03C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4DD92970278A4A5B88A1ECAB3ABDCED6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_517E1DE56CC14032836B1858AE41B6E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'navxdocs'
          slot-name: 'Production'
          package: .
          